backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: 'src/assets/images'
public_folder: '/_astro'
locale: 'id'

publish_mode: editorial_workflow

collections:
  - name: 'artikel'
    label: 'Artikel'
    folder: 'src/content/artikel'
    create: true
    fields: 
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Gambar Unggulan", name: "image", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Kegiatan", "Publikasi", "Pendidikan", "Sejarah"] }
      - { label: "Tag", name: "tags", widget: "list", default: [], allow_add: true, allow_delete: true, collapsed: false, field: { label: "Tagar", name: "tag", widget: "string" } }
      - { label: "Penulis", name: "author", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Draft", "Published", "Archived"], default: "Draft" }