backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
site_url: 'https://pmiikomfakdish.or.id'

editor:
     preview: true
media_folder: 'src/assets/images'
public_folder: '/_astro'
locale: 'id'

publish_mode: editorial_workflow

collections:
  - name: 'artikel'
    label: 'Artikel'
    folder: 'src/content/artikel'
    create: true
    fields: 
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "publishDate", widget: "datetime" ,date_format: "DD.MM.YYYY", time_format: "HH:mm", hint: "Tanggal dan waktu publikasi artikel."}
      - { label: "Tanggal Update", name: "updateDate", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", hint: "Tanggal dan waktu update artikel."}
      - { label: "Gambar Unggulan", name: "heroImage", widget: "image" }
      - { label: "Alt Gambar", name: "altImage", widget: "string", hint: "Deskripsi singkat gambar untuk aksesibilitas" }
      - { label: "Isi", name: "body", widget: "markdown" }
      - { label: "Deskripsi", name: "description", widget: "markdown", hint: "Deskripsi singkat artikel untuk SEO tampil di halaman publikasi" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Kegiatan", "Acara", "Berita", "KOPRI", "Kalam Biru"] , allow_add: true , allow_delete: true, collapsed: false, allow_multiple: true, field: { label: "Kategori", name: "category", widget: "string" } }
      - { label: "Tag", name: "tags", widget: "list", default: [], allow_add: true, allow_delete: true, collapsed: false, field: { label: "Tagar", name: "tag", widget: "string" } }
      - { label: "Penulis", name: "author", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["draft", "published", "archived"]}
display_url: site_url

